### ISSUE TITLE
Not able to import Prometheus.zip into xmatters

### ISSUE THREAD

**Issue by mattharr-is** [xmatters/xm-labs-prometheus#7]
Hello,

I just tried to import this workflow with xmatters and was met with an "Invalid zip file format" error. Did something change recently about template import formats?

**Comment by xMTinkerer** [comment]
Hrm. I was able to import this into two different environments:
https://github.com/xmatters/xm-labs-prometheus/blob/master/Prometheus.zip

Note that you don't "open" the zip, just import it as is. Nothing should have changed. Can you provide any other details? Maybe try redownloading it?

**Comment by mattharr-is** [comment]
So frustrating, sorry for creating a ticket. Prior to raising the ticket, i had re-downloaded the file twice, unzipped it and re-zipped it, and it consistently would not work. I just re-downloaded again and was able to import the workflow. 4th time is a charm i guess.

Thanks!

**Comment by xMTinkerer** [comment]
Bummer, sorry about that. I had advocated for an extension other than .zip for these things, I might have to revive that conversation because you aren't the only person who assumes that a zip file should be unzipped. 

I'll close this issue, but hit us back if you run into anything else.

**Comment by mattharr-is** [comment]
just to be clear, i didn't assume it needed to be unzipped. the zip file was just corrupted after multiple re-downloads, so i tried unzipping/rezipping.
